mutation CreateStudent($input: StudentCreationInput) {
    createStudent(input: $input) @client {
        lastname
        firstname
        email
        classId
        lessons {
            completion
            successRate
        }
    }
}