#import "./studentFragment.gql"

query getStudent($id: ID!) {
    student(id: $id) @client {
      ...studentFragment
    }
    next(id: $id) @client {
      id
    }
    previous(id: $id) @client {
      id
    }
}